POST http://localhost:8080/api/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5aG9uaSIsImlhdCI6MTY5MjAzOTUyNSwiZXhwIjoxNjkyNjQ0MzI1fQ.LEWUY5E2yAsk01_L_M5mV3Serv72kgXm7SAycneWFJg

{
  "content": "test 1",
  "title": "test 1"
}

###

GET http://localhost:8080/api/post
Content-Type: application/json



###

GET http://localhost:8080/api/post/61af31d7-87ae-4743-a431-484e3e439df7



###
PUT http://localhost:8080/api/post/61af31d7-87ae-4743-a431-484e3e439df7
Content-Type: application/json

{
  "title": "asd",
  "content": "asd"
}

