spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: yhoni
    username: yhoni
    url: jdbc:postgresql://postgres-local-dev/blog-app-dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database: postgresql
    # properties:
    #   hibernate:
    #     show_sql: true
    #     format_sql: true

app:
  jwt_secret: secretkey
  jwt_expiration: 604800000

server:
  port: 5000

springdoc:
  swagger-ui:
    path: "/"
